### ISSUE TITLE
Block registration states 4 new block types created, but UI shows 6 new block types

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect-dbt#91]
I think the the block registration message needs updated when `prefect block register -m prefect_dbt` is run.
I had no dbt blocks showing in the uI prior to running the registration command.

Screenshots attached.
<img width="997" alt="Screen Shot 2022-11-08 at 3 01 18 PM" src="https://user-images.githubusercontent.com/7703961/200663211-c852ba30-95ba-4090-b8f2-24dccdd7f073.png">
<img width="780" alt="Screen Shot 2022-11-08 at 3 01 43 PM" src="https://user-images.githubusercontent.com/7703961/200663290-26ac7642-70c6-4635-86f5-3fc79fbb619c.png">

**Comment by ahuang11** [comment]
I think it's because the [top level `__init__`](https://github.com/PrefectHQ/prefect-dbt/blob/main/prefect_dbt/__init__.py) has:
1. DbtCloudCredentials
2. DbtCliProfile
3. SnowflakeTargetConfigs
4. BigQueryTargetConfigs
5. PostgresTargetConfigs (but you don't have the postgres requirements installed so it's not registered)

This results in +4.

This makes it search the [CLI directory `__init__`](https://github.com/PrefectHQ/prefect-dbt/blob/main/prefect_dbt/cli/__init__.py) finding the two other:
1. TargetConfigs
2. GlobalConfigs
+ 2 = 6 that you see on Cloud.

This is probably a "bug" or unexpected feature of Prefect's block discovery logic, not particular to prefect-dbt, but any package that has this structure.

However, I think I should expose TargetConfigs and GlobalConfigs blocks at the top level too for `prefect-dbt`.
